
const Content = [
    {
        img:"../img/searchIcon.svg",
        id:1,
        author:"a",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2",],
        category:"배달",
    },
    
    {
        img:"./img/searchIcon.svg",
        id:2,
        author:"a",
        title:"이거 같이 살 고등어사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"배달",
    },
    {
        img:"./img/searchIcon.svg",
        id:3,
        author:"a",
        title:"이거 같이 살 사람~~이거 같이 꽁치살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"오프라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:4,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살꽁치 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"오프라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:5,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 양파사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"오프라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:6,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"오프라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:7,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"배달",
    },
    {
        img:"./img/searchIcon.svg",
        id:8,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"온라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:9,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"온라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:10,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"온라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:11,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"온라인",
    },
    {
        img:"./img/searchIcon.svg",
        id:12,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"배달",
    },
    {
        img:"./img/searchIcon.svg",
        id:13,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"배달",
    },
    {
        img:"./img/searchIcon.svg",
        id:14,
        author:"b",
        title:"이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~이거 같이 살 사람~~",
        item:"스니커즈",
        limit:3,
        participants:["user1","user2", "user3"],
        category:"배달",
    },
    
]
export default Content;